# Generated by Django 3.2.19 on 2023-07-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_oauth_id_token', models.CharField(max_length=100)),
                ('twitch_oauth_refresh_token', models.CharField(max_length=100)),
                ('twitch_username', models.CharField(max_length=30)),
                ('twitch_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('start_z', models.IntegerField()),
                ('end_x', models.IntegerField()),
                ('end_y', models.IntegerField()),
                ('end_z', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show')),
            ],
        ),
        migrations.CreateModel(
            name='MiniConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='app.region')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='app.region')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='CrowdSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('minimap', models.BinaryField(max_length=102400)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show')),
            ],
        ),
    ]
