# Generated by Django 3.2.19 on 2023-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230722_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
