# Generated by Django 3.2.19 on 2023-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_show_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniconfig',
            name='name',
            field=models.CharField(default='Unnamed', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miniconfig',
            name='limit',
            field=models.IntegerField(default=-1),
        ),
    ]
