# Generated by Django 3.2.19 on 2023-07-22 07:25

import crowd_computing.app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230722_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniconfig',
            name='name',
            field=crowd_computing.app.models.UrlSafeCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=crowd_computing.app.models.UrlSafeCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='twitch_username',
            field=crowd_computing.app.models.UrlSafeCharField(max_length=30),
        ),
    ]
