# Generated by Django 3.2.19 on 2023-07-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230722_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='minecraft_auth_secret',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
