# Generated by Django 4.2.3 on 2023-07-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230724_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsource',
            name='range',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
